[package]
name = "opensubsonic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opensubsonic-macro = { path = "./opensubsonic-macro" }
async-trait = "0.1.74"
percent-encoding = "2.3.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
time = { version = "0.3.30", features = ["serde", "macros", "parsing", "formatting", "rand"] }
axum = "0.7.2"
tokio = { version = "1.35.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tower-http = { version = "0.5.0", features = ["trace"] }
tokio-stream = { version = "0.1.14", features = ["full"] }
bytes = { version = "1.5.0", features = ["serde"] }
