action-name: release
on:
 push:
   tags:
     - "[0-9]+.[0-9]+.[0-9]+*"
jobs:
  release:
    runs-on: [fedora-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
