[package]
name = "sonar-extractor-lofty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sonar = { path = "../sonar" }

lofty = "0.18.2"
tracing = "0.1.40"
